Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    MatchDriver "libinput"
    Option "NaturalScrolling" "true"
    Option "Tapping" "true"
    Option "ScrollMethod" "twofinger"
    Option "DisableWhileTyping" "true"
EndSection

